---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth1",
          "mode": "bridge",
          "ipam": {
            "type":"static",
            "routes": [
              { "dst": "192.168.0.0/16", "gw":"192.168.2.1"}
            ]
            }
          }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }
