---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        # Yo dawg I heard you like go templating so I put go templates in your go templates
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: alertmanager
