apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:BQpapNSkiXaSCMpVwJu/huwLFwCKTImrVoqBaK+U7BWgrP0R,iv:2VVpQ3pR0XU34LDi8mEyqAQIbkG5H+lS736egaQdv9U=,tag:YpGDH1WDQYZZcZLRg/C4fg==,type:str]
    credentials.json: ENC[AES256_GCM,data:uoDXvM4b29RgdysnkBkzP2WXU/o0ohZp1mAUx0vgmU/0K+UH0H5aUKebbjj9t8bw/N51GV5tMvgHTtsR4QSt4T3R3soRseq30AOrqKYdbdMWGlaD4ZqlcIN73ZMTZ3Mwcb6TvrkKc1RNUBIRpxeRTlCdwucB/MsBoNs6kB8qC7uKaSCFnydUe6EzQxBz9bSm8DSCoaazFadZsbk7AJUbWe2k8xs5bdtk29W6tndMwA==,iv:P5o+dKJy9ru+UI4ps1frAlE30DgPRvVFanhIJdB+IPw=,tag:/yfTIw1bE4ikLZCKzBLqRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZzZUWjhhRU5SNjdZTVl4
            bVBtU2hFN0dHSjJsbm5DTEVhMDlzc0g0QnlRCkFFbWRSb2VPSFFRcXpYcHB6MUZl
            bUJsMk9YRHBDbUhXK3ZXbW1ITFEwdEkKLS0tIHIzSk9pSjcrZjFlaEk2cHRldnJQ
            UEkxcWxZRGZ1VG43RnZscVc5eEFnRFkK/Rwav5zHG5zMyj2O7VX0y1k07vIKMDsU
            uVctlcFvt/1SoXcOT7wLVJ94v+M35TeLtYkRHAbWMTaJbs7nISILeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T10:32:01Z"
    mac: ENC[AES256_GCM,data:QHvL1Zi0gS6yi+ks3vGYOt9u5fJxcxdWZy+Dy1OFNsXZblx0Rqo585JtGCpyHy+e5b5p6NQMahGDJHSrpaBNdPR19o4GCFiM4wJcq63EXwdmAFLECnv1/aIKYogFHiC9ln1pyjpYabfIH0QYwUPof6tebPhbfvhRUMxrqTaL62I=,iv:M2ylL9l+1PUlWKdSkl88nNVd459FogBz/+R+wRHu/XM=,tag:Gsp3nwnKUfdr6bdW442yeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
