apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hWJ746Dx4oeEmLpNy+7K08kGWzXvhDM/R2fuyxYHva1/vAYa,iv:bahfJrh8JwWbWlGNBhOnChYT4/wxyZDuBu9g1dpFJ8s=,tag:+zuDODMFJjdSXpGMvd50Mg==,type:str]
    credentials.json: ENC[AES256_GCM,data:MULKbt8+qQoRrD9cJoluKSqKlF927Fh3AeG0eaeajCxakXICmFPpgbH8Hd2ad/kjBPfWqwBCSk0BFsrIIPkISJILrB4xqxiql9fxo2VNXRWX0o8mhLyEXEjD8tF9rnW31DrOgrEWqXZqRAoTm4EtIQh1vSjLEb1TBQvrt4PT2wrer2cUzpyold6hMiC2kktw7rLL3vtS4WoQxMqEu7qx/B9Q2++6wpOQd2gJ+wFvXA==,iv:uJ1w13YYtxOqBlbPz+p2EbGkvXys+pqph14TXh0JMJ4=,tag:TC6w++8VsTHM5qtZmcVUjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRVlCQnhoNWZoc0xlZ0lw
            TW91YlVOYWRMZ1J6ZjlCMWJCWWtEamNsSGhRCkVjUkFJVXdFeEdhSGhrSnRxMGpK
            YVgrMVNRL1QzUmdEWmN2QXZnbmw5TFUKLS0tIHgxcS9TWURuQXpyaEdacUJJOGVm
            R3k5V1cwVWV3aC9FeDZDN0huaU9leXMKaYhNh8Zuh8Ppivb6mkNUFKQgUVhZ/iK9
            VdDR81tpTPXFiJAT8HBHTSvTss9fqms86esJ1n0+WiopaZj9cJ2a7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:29:06Z"
    mac: ENC[AES256_GCM,data:Q2tYnylNj30aZeWCPQq3OpplcvcKiB5KpykOAHBaeQ6wGqfeRYjZTD00BubDQOqtGJOeDcZOZgZtnac2vSqYJ9dCEvt9Qzf5LttWrQRVRqORaVI25eHMnlqCFd0qbrwTpY1URNJE1gNzpGTbn6tDJQ8DWEKO6JPQhYfRuxB+BW8=,iv:Ae5PUuQW+lYbs7t9BiQ9qodNAuU0xluq7TcG2qgEDKA=,tag:HKEL4sccFmCYFeq6h9a85w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
