---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  path: "./deploy"
  sourceRef:
    kind: GitRepository
    name: kubevirt
  dependsOn: []
  patches:
    # namespace is managed separately by main ks, no need for this ks to also manage it, KubeVirt bundles namespace into kubevirt-operator.yaml
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: kubevirt
      target:
        kind: Namespace
        name: kubevirt
    - patch: |
        apiVersion: kubevirt.io/v1
        kind: KubeVirt
        metadata:
          name: not-used
        spec:
          configuration:
            vmStateStorageClass: "file"
            developerConfiguration:
              featureGates:
                - VMPersistentState
                - DataVolumes
                - AutoResourceLimitsGate
                - LiveMigration
      target:
        group: kubevirt.io
        kind: KubeVirt
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-cdi
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  path: "./deploy"
  sourceRef:
    kind: GitRepository
    name: kubevirt-cdi
  dependsOn: []
