apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:l78LRNAxtEiPF7xryTqeVDOpKQC+xY3HcaEpdtCHaeVSJYCmRL2LjA==,iv:RMN0/Ctl6GgshdwsGXcR529nuGomZXT+h4+Z2nl+HQU=,tag:VjLdZTf0jQ6lBBLh0LL8tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Wmt1cUFqdnArU3NrV0cx
            bWg4Vm9kRWdBdUZqajlpcTMwVkpmNFM5cjFnCmxWWUNselFRSTZWQVNNVUR3d3dk
            WGdVaXdodGllR0RCTFAwQkhPNzM4Zk0KLS0tIHpzSkJabjBQb3Nxa3BlUUlEK1c2
            MGpOaStSTDI5RmtQWTZSaVZOSHdFWTQKg6jA5lLnuHee52jlZcD/UV7Z1z8AzoiL
            y72WfQCimM0j90ijNzXJZTApBf1B7JaEkQZjHakZL2fBnaTvU1B7eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T21:57:13Z"
    mac: ENC[AES256_GCM,data:vEyabKU4jA4sDyss7fZIesFQivP2XcPHePmKNESnWYuvc2iCCyUD+erKJuCj5uEtYGK9HMb5v6Sx4JS+aEcDFjePpf2rIe1kMtOFco6FFLJQkYXB4l//tn+iwzQhvrQakFOvvLDjNeJhUh5J8YO6cFPfhJBiWNEu6YyDTumK/XU=,iv:6zoKPj11ZZjVwZJ+UH3qSRXNd3MKnTVZKZRhk33Lrkg=,tag:3Uq8GcrluKtmPVBm5k140Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
