---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  targetNamespace: home-assistant
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kubevirt
    - name: rook-ceph-cluster
    - name: cloudnative-pg-cluster
    - name: multus-networks
  path: ./kubernetes/apps/home-assistant/home-assistant/vm
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
