apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tjL3arG3W+4O,iv:9OLCDBmG307p54BDP/B1RwjaMrw499IpBYTOHIL6eic=,tag:v73rbePvjk1qI81NcM5tZg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ENRKa0Dx3tDcTxgDWfHHIqCMWGx1xvnF,iv:jpObl857Iab1vTu7d72E3ewXyIUxq7MzOCmj6/papdw=,tag:wMMPyFY2BgQMAR9hpJP7Og==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:B96tqun3YAx3m431W6qsaTBXCcsejxVD0XntwASeFjO1jL6J,iv:SQzKenoIotLatAkwurnsgacnUr8RRuW8zxwCt6LVOJs=,tag:54pTRVbf0W4ONflsOb4/Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMFBNU04waXl6cmsxL2dW
            eTE2V2xvT1ErYmZIUzJNdGF5a2ExSWIrRWlBCkk1Q2tMSVRjeTRickFRQ0RJdGR4
            bWZzZjNkdTdHVE9zNDV2RFBvaHdFa2sKLS0tIG1USDJyUUhzNEViaHdGVkRpSExY
            QVUvbk1DMUk1a2txbXRTSkNDT1VBOEkKVTA5I86kKTWY82/9/u4exmReKgcw6Ixd
            zLbh8rRtcfa3/7h6uPU3bL7PkPY9fnVn6ChYf8K1tL7uQaJGNtmWOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:29:06Z"
    mac: ENC[AES256_GCM,data:2BY0F1hjDQc8lZAWQ/cpldPttPC0oIfJ0dlc5gUxLeBFR7CDiG3plsj9OdAGYNJqRIcpjbv0cgph9BowxeYu6UoArG2QvhwJ9TRXo72KsRgKeorIue62MRFOJeZ6fKedm5399fna1dsWrLdNIsNy72C/uCT4wllLca2md+D8qy4=,iv:YDJClJHYhZQb6kB8hvaXrH9Ud7n9ru8KLw5mM/0VpNQ=,tag:lK3DnvERS2o0Z2Ox7b7iCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
