apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:idLyUSTCQsuD/LK35DtNkW9xUketn8TPF4X1GkoKr4o=,iv:ZEOJmdiq1RBRs8sBAm0sRt2ni044jiGEvWmAw7aGSjg=,tag:nN9Sp2ek4ya2L3KZ+vnYww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRTlWL3BRZ0F0SEp1L292
            Z09RLzNUUlNmS2ZOUlcwdmtDeWFqUWJhNnlJCi84am0rU250Q0l6NW9JS2xLdS9R
            VGxHdFFHQzRKdW0xUzRMT1p1UHRoeWsKLS0tIDRDYnJmV1lZcDhwNTJFWHF1d2lM
            dWpGWmdtT1d3d1E2aFVTM0pVWEdRVmcK10nMEJIklJu0sQt6PkZane1ng4Hkxrjp
            4y5xeU/y5GKScdIBGa2pUlPZbURg8khdJTvp1vqHp2eEkRL1wXkr2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T09:40:05Z"
    mac: ENC[AES256_GCM,data:gUyQ4kzMK3UD0g9rbFiiTDfAwklcKodWlvLTp8SIyM5Mw6Wcf6ttV7RFRk092+W2hL2Q7eiU8KwJ5SrtKUl/u87V863H+1Dodxb7RpkNfiUHq7sEQ6FjzP5P4owlYqM4YR+7yy0TvpMmTHjBnz7SDgt2z7SBJuMjAUSvlx0n370=,iv:Dc+u2PgGSILjN/Yo/0JEHv/OG11VYIMFr1KY2iVTL/w=,tag:j/JCF9/TBufMr5QZwHMB3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
