apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:zl4aDPW3OAbBYp54IKSjhLnfnWXaXSsJ7b6/1SwiJeE=,iv:FDjbJtM7L66jCum2zeW/BnO8xD88DcrlU0dtx8bPu2U=,tag:oWp5YuQZ8QDx+lrbMpGsPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bkpJN1JJT2tvVktFalpT
            QW9td0VKbFhEcEk0OUFEczJCTG1MWVNWdm40CnJRY1ZyaUFEc2NSWWdiWVNIU1M2
            T0pKamJZVmVEeU9pQUFrOXZnaXdYTzQKLS0tIEVPQjJlWFFYS1EwU2dxanc1cnpl
            NXVBeVN2dFM5a0VzMXZiSlZQN1pJdWcK8d8M5pCKNynYz7ZDJdeSblY8Wbj9UY9B
            tijAeIODwPLUeAq7nUZGo9GeiSNwPSITAcmTpiUJYvmmovBFn2f2LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:29:06Z"
    mac: ENC[AES256_GCM,data:cl4mtEX+atV7hPEkjYdReg492tDEA50A4BOAaE6fTutUm1HOSfErcn1IUeXNOw0gQWGPnARaWrDR8GJdFtv+oEQr5ywgYtWzY8PyL2sgH7O9dolv4+uz0rAzDJ7yeiaffMTVYpRVsFog6pkvmGhdFMgFMuTWg1F03k3O/K9/2CE=,iv:I+Luydojpm3TAiFKSw6c0cRMmr+h6IHpPDnzOQuTq3w=,tag:4dpzvv/+1kR4AAqwvWCGrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
