---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: testvm
  namespace: kubevirt
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "testvm",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "br0",
          "capabilities": { "mac": true },
          "ipam": {}
        }
      ]
    }
