apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:607RXT8Uj1wHl8IbPLyhOKSEUd0y5cmNifTNmaQgGzPlQQgem6qgeQ==,iv:U+A87/J5f1qAG5W73NUFpUelTR6gnACBzCLkyrzgfC0=,tag:89LHU2skv+j4/L6Qn0IYuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc0NOUnBOaHVvazBKYnl5
            MG5LeWFCVGF3Skp2VVlsdTJ2N21wM2ZRQmlnCkI1elU4UGIzZVZ2ZjJBTWZDNm5C
            WmxhWlozWUxhNzN4OHNma1E5aE5FL0kKLS0tIFpwaXFnaGNSM1lTaXFNb3c1cVZj
            NUlHV0dKTXFzMjA2QWJ6ekh5ZzRUdGMK8F40qnRwM1Dnuq5bgB2duXQwIrKtlFML
            UKnk/quFMCxtLtP5fA1jLet/uSEvmoyCh3UJmoBB6rQuwKoHzHM+0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T09:40:05Z"
    mac: ENC[AES256_GCM,data:2AICFKdLVtp+5m3uJQBm5v6ub62SEdevUrCfNku8cctM2k9U/QoORUK5x8ornB3gr3wBaW1c8h8sRADFcZQ8TeleiOJRuXQDZM1Jji/0Sc5xw3c1Lnz/Sa2aeQC+9EOWHD/V5GO2/w5PTt5OcA5n+4TN8Thnc6X6WXWksfuFlyI=,iv:HAIzZPCmAwcEF+d2fSWYsS1UKNDPn7EXNHNd7iqHOsY=,tag:FsPqJbtpO4KK7BkVkz4+ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
