---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
spec:
  provider:
    aws:
      service: ParameterStore
      role: arn:aws:iam::291717560534:role/SSM-External-Secrets
      region: ap-southeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm-auth
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-ssm-auth
            key: secret-key
            namespace: external-secrets

